apiVersion: v1
kind: ConfigMap
metadata:
  name: smartloss-config
  namespace: smartloss  
data:
  FRONTEND_URL: "http://smartloss-frontend.smartloss.svc.cluster.local"
  VITE_BACKEND_URL: "/api"
  


  

